### ISSUE TITLE
[parse-markdown-table] Table dashes are being parsed as row data

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ksxnodeapps/fun-little-utilities#159]
This is what the markdown table I'm trying to parse looks like:
```md
name | age
-- | --
Toby | 3
Alex | 25
```

You can see that it's a valid format:
name | age
-- | --
Toby | 3
Alex | 25

But when I call `createMarkdownObjectTable()`, it includes the `-- | --` row.
```json
{
  "name": "--",
  "age": "--"
}
```
...actual row data.

Link to reproduce: https://codesandbox.io/s/parse-markdown-table-bug-54xci?file=/src/index.ts

**Comment by KSXGitHub** [comment]
It was an oversight on my part. But I'm busy right now, so I can't fix this any time soon. You may either create a pull request or temporary workaround this by eliminating the first row.
