### ISSUE TITLE
[parse-markdown-table] Synchronously parse

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ksxnodeapps/fun-little-utilities#162]
Since parsing the markdown doesn't involve any I/O operations, it can be synchronous.

## Current example function
```ts
function iterateRows(lines: Stream, options: TableIterationOptions): AsyncGenerator<string[], void, unknown>
```

### Add synchronous overload to existing functions
Breaking? no
```ts
function iterateRows(lines: Stream, options: TableIterationOptions): AsyncGenerator<string[], void, unknown>
function iterateRows(lines: Iterable<string>, options: TableIterationOptions): Generator<string[], void, unknown>
```

### Add synchronous functions which end with `Sync`
Breaking? no
```ts
function iterateRows(lines: Stream, options: TableIterationOptions): AsyncGenerator<string[], void, unknown>
function iterateRowsSync(lines: Iterable<string>, options: TableIterationOptions): Generator<string[], void, unknown>
```

### Make existing functions synchronous and asynchronous functions end with `Async`
Breaking? yes
```ts
function iterateRowsAsync(lines: Stream, options: TableIterationOptions): AsyncGenerator<string[], void, unknown>
function iterateRows(lines: Iterable<string>, options: TableIterationOptions): Generator<string[], void, unknown>
```

- [x] I can make a PR for this

**Comment by KSXGitHub** [comment]
> [x] I can make a PR for this

I will be waiting for your result.

> ### Add synchronous functions which end with `Sync`
> Breaking? no
> 
> ```ts
> function iterateRows(lines: Stream, options: TableIterationOptions): AsyncGenerator<string[], void, unknown>
> function iterateRowsSync(lines: Iterable<string>, options: TableIterationOptions): Generator<string[], void, unknown>
> ```

Let's go with this.
